# Generated by Django 5.1.1 on 2024-09-18 04:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(max_length=255)),
                ('bloco', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('andar', models.CharField(choices=[('T', 'Terreo'), ('P', 'Primeiro'), ('S', 'Segundo')], max_length=1)),
                ('adicionado', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('adicionado', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_destino', to='rotas.ambiente')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_origem', to='rotas.ambiente')),
            ],
        ),
    ]
